export const CONFIG = {
    floorWidth: 12,
    floorHeight: 0.8,
    floorDepth: 12,
    floorFriction: 1,
    floorRestitution: 0.5,
    numSpheres: 1,
    sphereStartY: 50,
    gravity: -9.81,
    forceMagnitude: 1000,
    cameraShiftSpeed: 20,
    floorSpawnInterval: 1000,
    isLighted: true,
    shadowSize: 300,
};